[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "sh ./railway/init-app.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
